/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthProfile {
  'username' : string,
  'password' : string,
  'createdAt' : bigint,
  'isPublic' : boolean,
  'profilePicture' : [] | [ExternalBlob],
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Comment {
  'id' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'author' : Principal,
  'reelId' : bigint,
}
export interface Conversation {
  'id' : ConversationId,
  'participantA' : Principal,
  'participantB' : Principal,
  'createdAt' : bigint,
}
export type ConversationId = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : MessageId,
  'createdAt' : bigint,
  'text' : string,
  'sender' : Principal,
  'conversationId' : ConversationId,
  'replyTo' : [] | [MessageId],
  'reactions' : Array<Reaction>,
}
export type MessageId = bigint;
export type Principal = Principal;
export interface PublicProfile {
  'username' : string,
  'isPublic' : boolean,
  'profilePicture' : [] | [ExternalBlob],
}
export interface ReactInput { 'messageId' : MessageId, 'emoji' : string }
export interface Reaction { 'emoji' : string, 'author' : Principal }
export interface Reel {
  'id' : bigint,
  'likeCount' : bigint,
  'video' : ExternalBlob,
  'createdAt' : bigint,
  'filename' : string,
  'caption' : string,
  'commentCount' : bigint,
  'uploader' : Principal,
  'saveCount' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SavedReel { 'savedAt' : bigint, 'reelId' : bigint }
export interface SendMessageInput {
  'text' : string,
  'conversationId' : ConversationId,
  'replyTo' : [] | [MessageId],
}
export interface Status {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'author' : Principal,
  'image' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Adds a comment to a reel as the caller.
   */
  'addComment' : ActorMethod<[bigint, string], Comment>,
  /**
   * / Uploads a new reel with a caption. The video is stored via the
   * / object-storage extension; only the external blob reference is kept here.
   */
  'addReel' : ActorMethod<[string, ExternalBlob, string], Reel>,
  /**
   * / Posts a status/note as the caller. `text` must be non-empty and at most
   * / 280 characters. `image` is an optional external-blob reference produced by
   * / the object-storage extension.
   */
  'addStatus' : ActorMethod<[string, [] | [ExternalBlob]], Status>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Change the caller's password. Requires the current password to match;
   * / returns false otherwise or when the caller has no profile.
   */
  'changePassword' : ActorMethod<[string, string], boolean>,
  /**
   * / Change the caller's username. Returns false when the new username is
   * / already taken by another user or the caller has no profile.
   */
  'changeUsername' : ActorMethod<[string], boolean>,
  /**
   * / Deletes one of the caller's own statuses/notes.
   */
  'deleteStatus' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static API documentation for the Baathchit backend. Authored from the
   * / current source; read-only and returns no runtime state.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Fetch the caller's own profile (username/password) stored against their
   * / Google account. Returns null when the caller has not registered yet.
   */
  'getCallerProfile' : ActorMethod<[], [] | [AuthProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrCreateConversation' : ActorMethod<[Principal], Conversation>,
  /**
   * / Returns a single reel by id, if it exists.
   */
  'getReel' : ActorMethod<[bigint], [] | [Reel]>,
  /**
   * / Look up another user's public profile info (username, profile picture,
   * / visibility). Returns null when the principal has no registered profile.
   * / The frontend uses `isPublic` to decide whether to render that user's
   * / principal ID: when false, the ID must be hidden everywhere in the app.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [PublicProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Check whether a username is available for registration.
   */
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  /**
   * / Likes a reel as the caller.
   */
  'likeReel' : ActorMethod<[bigint], undefined>,
  /**
   * / Returns the comments on a reel.
   */
  'listComments' : ActorMethod<[bigint], Array<Comment>>,
  'listConversations' : ActorMethod<[], Array<Conversation>>,
  /**
   * / Returns the reel IDs the caller has liked, so like state can be reflected
   * / on feed load.
   */
  'listLikedReels' : ActorMethod<[], Array<bigint>>,
  'listMessages' : ActorMethod<[ConversationId], Array<Message>>,
  /**
   * / Returns all reels in the feed, newest first.
   */
  'listReels' : ActorMethod<[], Array<Reel>>,
  /**
   * / Returns the reels the caller has saved.
   */
  'listSavedReels' : ActorMethod<[], Array<SavedReel>>,
  /**
   * / Returns a user's statuses/notes, newest first.
   */
  'listStatusesByAuthor' : ActorMethod<[Principal], Array<Status>>,
  'reactToMessage' : ActorMethod<[ReactInput], undefined>,
  /**
   * / Set a unique username and password for the caller's Google account.
   * / Fails if the caller already has a profile or the username is taken.
   */
  'registerUser' : ActorMethod<[string, string], boolean>,
  /**
   * / Saves a reel to the caller's collection.
   */
  'saveReel' : ActorMethod<[bigint], undefined>,
  'schema' : ActorMethod<[], string>,
  'sendMessage' : ActorMethod<[SendMessageInput], Message>,
  /**
   * / Set the caller's profile picture (an external-blob reference produced by
   * / the object-storage extension). Pass null to clear it.
   */
  'setProfilePicture' : ActorMethod<[[] | [ExternalBlob]], boolean>,
  /**
   * / Toggle whether the caller's account is public (ID shown everywhere) or
   * / private (ID hidden from other users).
   */
  'setVisibility' : ActorMethod<[boolean], boolean>,
  /**
   * / Removes the caller's like from a reel.
   */
  'unlikeReel' : ActorMethod<[bigint], undefined>,
  /**
   * / Removes a reel from the caller's saved collection.
   */
  'unsaveReel' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];