/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'author' : IDL.Principal,
  'reelId' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Reel = IDL.Record({
  'id' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'video' : ExternalBlob,
  'createdAt' : IDL.Int,
  'filename' : IDL.Text,
  'caption' : IDL.Text,
  'commentCount' : IDL.Nat,
  'uploader' : IDL.Principal,
  'saveCount' : IDL.Nat,
});
export const Status = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'image' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AuthProfile = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'createdAt' : IDL.Int,
  'isPublic' : IDL.Bool,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const ConversationId = IDL.Nat;
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'participantA' : IDL.Principal,
  'participantB' : IDL.Principal,
  'createdAt' : IDL.Int,
});
export const Principal = IDL.Principal;
export const PublicProfile = IDL.Record({
  'username' : IDL.Text,
  'isPublic' : IDL.Bool,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const MessageId = IDL.Nat;
export const Reaction = IDL.Record({
  'emoji' : IDL.Text,
  'author' : IDL.Principal,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'conversationId' : ConversationId,
  'replyTo' : IDL.Opt(MessageId),
  'reactions' : IDL.Vec(Reaction),
});
export const SavedReel = IDL.Record({
  'savedAt' : IDL.Int,
  'reelId' : IDL.Nat,
});
export const ReactInput = IDL.Record({
  'messageId' : MessageId,
  'emoji' : IDL.Text,
});
export const SendMessageInput = IDL.Record({
  'text' : IDL.Text,
  'conversationId' : ConversationId,
  'replyTo' : IDL.Opt(MessageId),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [Comment], []),
  'addReel' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [Reel], []),
  'addStatus' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [Status], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'changeUsername' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteStatus' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(AuthProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrCreateConversation' : IDL.Func([IDL.Principal], [Conversation], []),
  'getReel' : IDL.Func([IDL.Nat], [IDL.Opt(Reel)], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(PublicProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likeReel' : IDL.Func([IDL.Nat], [], []),
  'listComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'listLikedReels' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'listMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
  'listReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
  'listSavedReels' : IDL.Func([], [IDL.Vec(SavedReel)], ['query']),
  'listStatusesByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Status)],
      ['query'],
    ),
  'reactToMessage' : IDL.Func([ReactInput], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveReel' : IDL.Func([IDL.Nat], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendMessage' : IDL.Func([SendMessageInput], [Message], []),
  'setProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [IDL.Bool], []),
  'setVisibility' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  'unlikeReel' : IDL.Func([IDL.Nat], [], []),
  'unsaveReel' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'author' : IDL.Principal,
    'reelId' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Reel = IDL.Record({
    'id' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'video' : ExternalBlob,
    'createdAt' : IDL.Int,
    'filename' : IDL.Text,
    'caption' : IDL.Text,
    'commentCount' : IDL.Nat,
    'uploader' : IDL.Principal,
    'saveCount' : IDL.Nat,
  });
  const Status = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'image' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AuthProfile = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'createdAt' : IDL.Int,
    'isPublic' : IDL.Bool,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const ConversationId = IDL.Nat;
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'participantA' : IDL.Principal,
    'participantB' : IDL.Principal,
    'createdAt' : IDL.Int,
  });
  const Principal = IDL.Principal;
  const PublicProfile = IDL.Record({
    'username' : IDL.Text,
    'isPublic' : IDL.Bool,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const MessageId = IDL.Nat;
  const Reaction = IDL.Record({ 'emoji' : IDL.Text, 'author' : IDL.Principal });
  const Message = IDL.Record({
    'id' : MessageId,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'conversationId' : ConversationId,
    'replyTo' : IDL.Opt(MessageId),
    'reactions' : IDL.Vec(Reaction),
  });
  const SavedReel = IDL.Record({ 'savedAt' : IDL.Int, 'reelId' : IDL.Nat });
  const ReactInput = IDL.Record({
    'messageId' : MessageId,
    'emoji' : IDL.Text,
  });
  const SendMessageInput = IDL.Record({
    'text' : IDL.Text,
    'conversationId' : ConversationId,
    'replyTo' : IDL.Opt(MessageId),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [Comment], []),
    'addReel' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [Reel], []),
    'addStatus' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [Status], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'changeUsername' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteStatus' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(AuthProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrCreateConversation' : IDL.Func([IDL.Principal], [Conversation], []),
    'getReel' : IDL.Func([IDL.Nat], [IDL.Opt(Reel)], ['query']),
    'getUserProfile' : IDL.Func(
        [Principal],
        [IDL.Opt(PublicProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likeReel' : IDL.Func([IDL.Nat], [], []),
    'listComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'listConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'listLikedReels' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'listMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
    'listReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
    'listSavedReels' : IDL.Func([], [IDL.Vec(SavedReel)], ['query']),
    'listStatusesByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Status)],
        ['query'],
      ),
    'reactToMessage' : IDL.Func([ReactInput], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveReel' : IDL.Func([IDL.Nat], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendMessage' : IDL.Func([SendMessageInput], [Message], []),
    'setProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [IDL.Bool], []),
    'setVisibility' : IDL.Func([IDL.Bool], [IDL.Bool], []),
    'unlikeReel' : IDL.Func([IDL.Nat], [], []),
    'unsaveReel' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };